# Generated by Django 2.2.4 on 2021-05-01 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210429_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(2021, 5, 1), verbose_name='%d-%m-%Y'),
        ),
    ]
