# Generated by Django 2.2.4 on 2021-05-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favbooks_app', '0002_auto_20210511_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourited',
        ),
    ]
