# Generated by Django 2.2.4 on 2021-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_auto_20210414_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Thoughts & Ideas'),
            preserve_default=False,
        ),
    ]
