# Generated by Django 2.2.4 on 2021-04-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Default Description'),
            preserve_default=False,
        ),
    ]
